
spring:
  mail:
    host: smtp.gmail.com
    username: prithika087@gmail.com
    password: lmti xhyq lfep gjlj
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true